openapi: 3.0.1
info:
  title: Common errors for Axpe Consulting APIs
  description: Common errors for Axpe Consulting APIs
  termsOfService: 'https://www.axpe.com'
  contact:
    name: API Tecnology Axpe
    email: tecnologiaApificacion@axpe.com
  version: 0.0.0

paths: {}
components:
  schemas:
    '400':
      description: Bad Request.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-400:
          messages:
            - alias: BadRequest
              message: Request parameter does not meet the requirements.
              type: ERROR
              description: The name must contain less than 10 characters.
    '401':
      description: Unauthorized
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-401:
          messages:
            - alias: unauthorized
              message: Unauthorized to access the resource
              type: CRITICAL
    '403':
      description: Forbidden
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-403:
          messages:
            - alias: Forbidden
              message: Forbidden resource
              type: CRITICAL
    '404':
      description: Not found
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-404:
          messages:
            - alias: notFound
              message: Resource not found.
              type: ERROR
    '405':
      description: Method not allowed.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-405:
          messages:
            - alias: methodNotAllowed
              message: The requested resource does not support http method 'HEAD'.
              type: ERROR
    '406':
      description: Un supported media type.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-406:
          messages:
            - alias: unsupportedMediaType
              message: Only application/json is supported.
              type: ERROR
    '415':
      description: Un supported media type.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-415:
          messages:
            - alias: unsupportedMediaType
              message: Only application/json is supported.
              type: ERROR
    '422':
      description: Un processable entity.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-422:
          messages:
            - alias: unprocessableEntity
              message: unprocessableEntity.
              type: ERROR
    '423':
      description: locked.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-423:
          messages:
            - alias: locked
              message: System is blocked.
              type: ERROR
    '429':
      description: Too many requests.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-429:
          messages:
            - alias: tooManyRequests
              message: You exceeded the limit. Try again in an hour.
              type: ERROR
    '500':
      description: Service error.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-500:
          messages:
            - code: serviceError
              message: 'Sorry, something has gone wrong.'
              type: ERROR
    '501':
      description: Not implemented.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-501:
          messages:
            - code: notImplemented
              message: Server does not support the unctionality.
              type: ERROR
    '502':
      description: Not implemented.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-501:
          messages:
            - code: badGateway
              message: Service is not available.
              type: ERROR
    '503':
      description: Service unavailable.
      allOf:
        - $ref: '#/components/schemas/Error'
      example:
        example-error-501:
          messages:
            - code: serviceUnavailable
              message: Server is currently unable to handle the request due to a temporary overload or scheduled maintenance. Please try again later
              type: ERROR
    Error:
      title: Error
      type: object
      description: General structure to representative the errors.
      properties:
        messages:
          type: array
          description: List of errors produced.
          items:
            type: object
            description: Details of the error produced.
            properties:
              code:
                type: string
                description: 'Error code. This field must be readable (human readable), therefore it should not be a numeric code, but an alphanumeric one. Obligatory field.'
                example: testError
              message:
                type: string
                description: Error description.
                example: Test error message
              type:
                type: string
                format: enum
                description: |
                  Error message severity.
                  CRITICAL- error that prevents the operation of the entire application.
                  FATAL - error that prevents the operation of a specific functionality.
                  ERROR - error that does not affect more features.
                  WARNING - application works but a warning has been generated.
                  INFO - operative info message.
                enum:
                  - CRITICAL
                  - FATAL
                  - ERROR
                  - WARNING
                  - INFO
              description:
                type: string
                description: Description whit the error in the field.
                example: The id must be greater than zero.
            required:
              - code
              - message
              - type
